# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(verbose_name='Submit time')),
                ('original_email', models.TextField(max_length=10000)),
                ('emergency_type', models.CharField(choices=[('CR', 'Crime'), ('OT', 'Other')], default='CR', max_length=2)),
                ('suspect_name', models.CharField(max_length=200)),
                ('marker_script', models.TextField(max_length=1000)),
                ('address', models.TextField(max_length=100)),
                ('suspect_traits', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=200)),
                ('optional_info', models.TextField(max_length=1000)),
            ],
        ),
    ]
