# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='marker_script',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='optional_info',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='suspect_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='suspect_traits',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
