# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_auto_20171020_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='emergency_type',
            field=models.CharField(choices=[('HR', 'Harrassment'), ('BG', 'Burglary'), ('RB', 'Robbery'), ('TH', 'Theft'), ('AR', 'Arson'), ('AS', 'Assault'), ('MD', 'Murder'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
